### ISSUE TITLE
can ffmpeg support video renderer ?

### ISSUE THREAD

**Issue by AhmedHumk** [jellyfin/jellyfin-exoplayer-ffmpeg-extension#82]
this is not an issue other than a request can we have ffmpeg tp render videos as well ?

**Comment by Maxr1998** [comment]
Not in this repo; there's an upstream issue at google/ExoPlayer#2159.

**Comment by AhmedHumk** [comment]
i guess this would help 

https://github.com/AhmedHumk/ffmpegVideoDecoder
